### PR TITLE
Fix finding buildConfig at the time of webhook push event

### LINKED ISSUE #35: Build not getting triggered when doing a master commit in case of different app and repo name
When you create an application(different repo and application name) using the launcher and do some master commit on GitHub or some webhook event, build is not getting triggered. It is reproducible every time.

Steps to reproduce:
1. Create an application in space.
2. Put application name and repo name different.
3. Launch application
4. Go to GitHub of the repository, do some changes and commit to master.
5. Check OSIO or OSO console, build is not getting triggered.

It is working fine, in the case of same application and repo name. Looks like a part remained untouched in fixing #27 

Related OSIO issue https://github.com/openshiftio/openshift.io/issues/3969

cc @hrishin @sthaha

### LINKED ISSUE #3969: Build not getting triggered when doing a master commit in case of different app and repo name
When you create an application(different repo and application name) using the launcher and do some master commit on GitHub or some webhook event, build is not getting triggered. It is reproducible every time.

Steps to reproduce:
1. Create an application in space.
2. Put application name and repo name different.
3. Launch application
4. Go to GitHub of the repository, do some changes and commit to master.
5. Check OSIO or OSO console, build is not getting triggered.

It is working fine, in the case of same application and repo name. Looks like a part remained untouched in fixing #3095 

The issue needs to be fixed in Jenkins Sync Plugin.

### PR DESCRIPTION
**Pull request by piyush-garg**
Previously we have fixed the issue of finding buildConfig if app name and repo name
are different by findind the buildConfig perfectly. This issue still occurs for
webhook event on master and build is not getting created.

So made a function in openshiftUtils to perfectly find the buildConfig and
used it at both places
Fixes #35
Fixes https://github.com/openshiftio/openshift.io/issues/3969

### CODE REVIEW

**Comment by piyush-garg** [comment]
Can you please review this patch @gabemontero

File: src/main/java/io/fabric8/jenkins/openshiftsync/PipelineJobListener.java [hunk 1]
```diff
@@ -257,54 +257,14 @@ private BuildConfigProjectProperty buildConfigProjectForJob(WorkflowJob job) {
...
-    } else {
-      logger.info("Able to find BuildConfig for namespace: " + buildConfigProjectProperty.getNamespace() + " name: " +
-        buildConfigProjectProperty.getName());
-    }
+    //Find the buildConfig if present with both name and label
+    BuildConfig jobBuildConfig = OpenShiftUtils.getBuildConfig(buildConfigProjectProperty.getNamespace(),buildConfigProjectProperty.getName());
 
     if (jobBuildConfig == null) {
-
+      /* Lets create a new buildConfig*/
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/PipelineJobListener.java]: Since you are in this path, it might be worth it for you all to port the concurrency fix we have for trying to create a BC when a delete (presumably from the OpenShift side) is in progress.

See https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/PipelineJobListener.java#L170 and surrounding code for reference.

File: src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java [hunk 2]
```diff
@@ -114,6 +104,51 @@ public synchronized static void shutdownOpenShiftClient() {
...
+      inNamespace(namespace).withName(buildConfigname).get();
+
+    if (jobBuildConfig == null){
+
+      logger.info("Not able to find BuildConfig for namespace: " + namespace + " name: " + buildConfigname);
+
+      logger.info("Finding BuildConfig for namespace: " + namespace + " with label gitRepository: " + buildConfigname);
+
+      /* BuildConfig and Repo Name are not same, lets find the buildConfig by label*/
+      BuildConfigList jobBuildConfigs = getOpenShiftClient().buildConfigs().inNamespace(namespace)
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java]: I need to fix this in our repo as well, as I forgot to handle this when I picked the original commit from you all that introduced this, but we should be using https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java#L154 here 

Even if you all don't want to port over the `CredentialUtils.getCurrentToken()` piece, a place holder/skeleton version of `getAuthenticatedOpenShiftClient`  would be good so that when we pull such commits into upstream, we can pick these changes as-is

File: src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java [hunk 3]
```diff
@@ -114,6 +104,51 @@ public synchronized static void shutdownOpenShiftClient() {
...
+  find the BuildConfig with name of jenkins job, if that is not present
+  that is our case then it will also try to find the buildconfig having
+  label with the name of jenkins job
+  if found return the buildConfig after both checks otherwise null
+  */
+  public static BuildConfig getBuildConfig(String namespace, String buildConfigname) {
+
+    logger.info("Finding BuildConfig for namespace: " + namespace + " name: " + buildConfigname);
+
+    BuildConfig jobBuildConfig = getOpenShiftClient().buildConfigs().
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java]: same here ... getAuth ...vs getOpen...

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java [hunk 4]
```diff
@@ -29,11 +31,13 @@
 import org.jenkinsci.plugins.workflow.job.WorkflowJob;
 
 import java.util.ArrayList;
+import java.util.Collections;
 import java.util.List;
 import java.util.Set;
 import java.util.logging.Logger;
 
 import static io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.joinPaths;
+import static io.fabric8.jenkins.openshiftsync.Constants.OPENSHIFT_LABELS_BUILD_CONFIG_GIT_REPOSITORY_NAME;
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java]: I don't see this constant being used in this file ... it is used in the other ones

**Review by gabemontero — CHANGES_REQUESTED** [review]
some suggestions with porting of this commit to upstream in mind @piyush1594

File: src/main/java/io/fabric8/jenkins/openshiftsync/PipelineJobListener.java (hunk 1 above)
Comment (hrishin) [reply src/main/java/io/fabric8/jenkins/openshiftsync/PipelineJobListener.java]: Thanks for this fix @gabemontero :+1:

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java [hunk 5]
```diff
@@ -103,12 +110,27 @@ public boolean shouldSchedule(Queue.Task p, List<Action> actions) {
           logger.info("Triggering Jenkins build on WorkflowJob " + wj.getFullName() + " due to running on kubernetes due to " + causeDescription(actions));
           return true;
         }
-        logger.info("Triggering OpenShift Build for WorkflowJob " + wj.getFullName() + " due to " + causeDescription(actions));
+
+        /* We are always finding the buildConfig by the the name of JenkinsJobName
```
Comment (hrishin) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java]: Remove this long comment and let's keep it into OpenshiftUtils.getBuildConfig() method if required.

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java [hunk 6]
```diff
@@ -103,12 +110,27 @@ public boolean shouldSchedule(Queue.Task p, List<Action> actions) {
...
+         This is failing in the case of repoName and buildConfigName and triggering a build by pushing to master
+         not same we need to find the buildConfig by gitLabel also as added in launcher backend and
+         we do in PipelineJobListener in case of initial creation
+         */
+        BuildConfig foundBuildConfig = OpenShiftUtils.getBuildConfig(namespace, buildConfigname);
+
+        /*In this case if buildConfig name is not same as jenkins jobName converted to buildConfigName
```
Comment (hrishin) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java]: Let's try to get rid of the comment. A better way could refactor the code by wrapping build request logic into a private method `triggerBuildRequest()`

_let method name says what this piece of code is doing_

**Review by hrishin — CHANGES_REQUESTED** [review]
@piyush1594 thanks for PR. Can we add unit tests as well?

**Comment by piyush-garg** [comment]
@hrishin @gabemontero Please review it once more, I have updated the PR. Thanks

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigWatcher.java [hunk 7]
```diff
@@ -96,6 +97,18 @@
   private Watch buildConfigWatch;
   private ScheduledFuture relister;
 
+  private static final ConcurrentHashSet<String> deletesInProgress = new ConcurrentHashSet<String>();
+
+  public static void deleteInProgress(String bcName) {
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigWatcher.java]: was there a reason you did not make a call to this method in your `deleteJob` method below? i.e. is your intent only to put some of the scaffolding for this fix in, or did you just overlook adding the call to this?

If the former, put some comments here indicating more changes are needed to fully activate.

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigWatcher.java [hunk 8]
```diff
@@ -96,6 +97,18 @@
...
+    deletesInProgress.add(bcName);
+  }
+  public static boolean isDeleteInProgress(String bcID) {
+    return deletesInProgress.contains(bcID);
+  }
+  public static void deleteCompleted(String bcID) {
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigWatcher.java]: same thing here ... if you want to fully implement, I would by a try finally in around the job.delete() call in `deleteJob`, where you call `deleteInProgress` right before `job.delete()`, and you call `deleteCompleted` in the finally block.

**Review by gabemontero — CHANGES_REQUESTED** [review]
@piyush1594 
- some questions / suggestions on your intent to introduce the delete in progress fix
- on the credentials piece, I think the runtime portion is OK, but I don't see any of the UI panels associated with it ... since you updated the constructor, etc. in GlobalPluginConfiguration, I would think you are going to need those panels, otherwise they might get a signature mismatch when someone actually tries to update the config

**Comment by piyush-garg** [comment]
@gabemontero So going through your comment it seems like a good amount of work unrelated to this issue, can we make that separate issue and PR to handle all these things. Because like openshiftclient is used at a lot of places in place of authenticated openshift client and as you said it needs other configuration in UI and same for delete job. cc @hrishin

**Comment by gabemontero** [comment]
@piyush1594 for the auth client sure we can wait until the next attempt at a rebase to consolidate the forks occurs.

The concurrent delete protection is more contained though, and there is some relevance to the change you are doing here, in that you are looking for BCs before creating them.  Are you good with consuming my comments here, and bringing that change in?

**Comment by piyush-garg** [comment]
Hey @gabemontero 

I am not touching the buildconfig creation part, but just adding one more filter for finding the buildconfig first as we have a use case of different build config name and repo name which is not there in current sync plugin. But I can do this part, please give me the link of upstream PR. That will be the better way and will reduce my effort. Thanks

**Comment by gabemontero** [comment]
On Wed, Jul 18, 2018 at 1:21 PM, Piyush Garg <notifications@github.com>
wrote:

> Hey @gabemontero <https://github.com/gabemontero>
>
> I am not touching the buildconfig creation part, but just adding one more
> filter for finding the buildconfig first as we have a use case of different
> build config name and repo name which is not there in current sync plugin.
>
but the filter is employed by the creation process

> But I can do this part, please give me the link of upstream PR. That will
> be the better way and will reduce my effort. Thanks
>
ok cool .... the pr is
https://github.com/openshift/jenkins-sync-plugin/pull/211

**Comment by piyush-garg** [comment]
@gabemontero I am just trying to get this concurrent delete protection PR in the fork and figured out that the functions you are changing are don't even exist till not here. Even `BaseWatcher` class does not exist here. I think we need to wait for rebase work for this also. Pardon me if I am wrong. cc @hrishin

**Comment by hrishin** [comment]
@piyush1594 at how many places we need to make changes for concurrent delete fix from upstream?Appears like its high time to priorties  _rebase work_.

**Comment by gabemontero** [comment]
On Thu, Jul 19, 2018 at 12:38 PM, Piyush Garg <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> I am just trying to get
> this concurrent delete protection PR in the fork and figured out that the
> functions you are changing are don't even exist till not here. Even
> BaseWatcher class does not exist here. I think we need to wait for rebase
> work for this also. Pardon me if I am wrong. cc @hrishin
> <https://github.com/hrishin>
>
That is correct, but there are analogous ones that you all have.  I noted
them in the earlier comment.  Look for where you call job.delete().

**Comment by gabemontero** [comment]
On Thu, Jul 19, 2018 at 12:55 PM, Hrishikesh Shinde <
notifications@github.com> wrote:

> @piyush1594 <https://github.com/piyush1594> at how many places we need to
> make changes for concurrrent delete fix from upstream. Appears like its
> high time to priorties *rebase work*.
>
Big +1 on that @hrishin

**Comment by piyush-garg** [comment]
@gabemontero I think we should avoid this patch here and make it part of rebasing work. I don't think that can be easily achievable. And this PR is getting blocked for that regarding finding buildConfig

**Comment by gabemontero** [comment]
that is fine @piyush1594 assuming @hrishin and the folks on your end agree - certainly you have to manage the competing concerns

**Comment by piyush-garg** [comment]
@gabemontero @hrishin Updated the PR. have a look. Thanks

**Comment by piyush-garg** [comment]
I just tested it with all the 4 cases and it worked fine in all 4. No duplicate pipeline and master commit creating a build for all.

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java [hunk 9]
```diff
@@ -84,8 +85,11 @@ public boolean shouldSchedule(Queue.Task p, List<Action> actions) {
       }
       if (triggerOpenShiftBuild) {
         String namespace = new GlobalPluginConfiguration().getNamespace();
-        String buildConfigName = JenkinsUtils.getBuildConfigName(wj);
-        String jobName = OpenShiftUtils.convertNameToValidResourceName(buildConfigName);
+        // This is the jenkins job name
```
Comment (hrishin) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java]: _could remove the comment, the variable name is good enough to understand_

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java [hunk 10]
```diff
@@ -84,8 +85,11 @@ public boolean shouldSchedule(Queue.Task p, List<Action> actions) {
...
+        String jobName = JenkinsUtils.getBuildConfigName(wj);
+
+        // This is the respective build config name of above job
```
Comment (hrishin) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java]: _could remove the comment, the variable name is good enough to understand_

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java [hunk 11]
```diff
@@ -103,21 +107,41 @@ public boolean shouldSchedule(Queue.Task p, List<Action> actions) {
...
-              .build()
-          );
-        return false;
+
+        /* We are always finding the buildConfig by the the name of JenkinsJobName
+         This is failing in the case of repoName and buildConfigName not same and triggering a build by pushing to master
+         we need to find the buildConfig by gitLabel also as added in launcher backend and
+         we do in PipelineJobListener in case of initial creation
+         */
+        BuildConfig foundBuildConfig = OpenShiftUtils.getBuildConfig(getOpenShiftClient(), namespace, buildConfigname);
```
Comment (hrishin) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java]: could rename method e.g. `OpenShiftUtils.findBCbyNameOrLabel(...)` that explain what this function does in order to get rid of comments.
Let code say what it does than comments explaining it?

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java [hunk 12]
```diff
@@ -103,21 +107,41 @@ public boolean shouldSchedule(Queue.Task p, List<Action> actions) {
...
+          triggerBuildRequest(buildConfigname, namespace, jobURL);
+          return false;
+        }
+
       }
     }
     return true;
   }
 
+  //This will trigger a build for the buildconfig with name buildconfigname
```
Comment (hrishin) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java]: `triggerBuildRequest(String buildConfigname,....)` is good enough to understand what it does? 
If yes then no need of comment.

File: src/main/java/io/fabric8/jenkins/openshiftsync/PipelineJobListener.java [hunk 13]
```diff
@@ -257,54 +255,15 @@ private BuildConfigProjectProperty buildConfigProjectForJob(WorkflowJob job) {
...
-          " with label gitRepository: " + buildConfigProjectProperty.getName());
-      } else {
-        logger.info("Not able to find BuildConfig for namespace: " + buildConfigProjectProperty.getNamespace() +
-          " with label gitRepository: " + buildConfigProjectProperty.getName());
-      }
-    } else {
-      logger.info("Able to find BuildConfig for namespace: " + buildConfigProjectProperty.getNamespace() + " name: " +
-        buildConfigProjectProperty.getName());
-    }
+    //Find the buildConfig if present with both name and label
```
Comment (hrishin) [inline src/main/java/io/fabric8/jenkins/openshiftsync/PipelineJobListener.java]: if we rename the method `OpenShiftUtils.findBCbyNameOrLabel(...)` then no need of comment here.

File: src/test/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtilsTest.java [hunk 14]
```diff
@@ -0,0 +1,77 @@
...
+
+import static io.fabric8.jenkins.openshiftsync.Constants.OPENSHIFT_LABELS_BUILD_CONFIG_GIT_REPOSITORY_NAME;
+
+public class OpenShiftUtilsTest {
+
+  @Rule
+  public OpenShiftServer server = new OpenShiftServer();
+
+  @Test
+  public void getBuildConfig() throws Exception {
```
Comment (hrishin) [inline src/test/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtilsTest.java]: Thanks for adding the test cases :+1: 

Can we do small refactoring?
Could extract setting mock expectations logic into a separate method so test case would become easy to read and understand.

**Review by hrishin — CHANGES_REQUESTED** [review]
@piyush1594 please could you go through one more round of review :)

**Comment by piyush-garg** [comment]
@hrishin Can you please take a look now?

**Review by hrishin — APPROVED** [review]
@piyush1594 LGTM :)
