### PR TITLE
Fix cancelling build when PR is updated

### LINKED ISSUE #38: PR build not getting triggered if build is already going on
Consider a scenario,  where you created a new PR. now a `repo-name.pr-1` pipeline will be created and `build 1` is triggered. Now if you push there a commit in PR while `build 1` is ongoing, `build-2` will not get triggered. Now after `build-1` get completed and now you push a commit to PR then `build-2` gets triggered. Ideally, it should trigger a build for every commit. 

1 pr build
gh-pr-build

@gabemontero this is the issue I was asking for concurrent build property. I am not sure whether this is some issue in sync plugin or an issue of Jenkins property or both.

Don't know whether `Allow concurrent build` property is relevant to this.

cc @hrishin @rupalibehera

### PR DESCRIPTION
**Pull request by piyush-garg**
This will add the feature of cancelling PR build
if the PR is updated as the previous change is no more
meaningful
If you update a PR which is building it will cancel the build
and will schedule a new one.
If you update a PR whose build in in queue it will
remove that build from queue and schedule new one

Add the flag `cancelPRBuildOnUpdate` to enable this feature
otherwise making this flag false will build all PR updates

Fixes #38
Fixes openshiftio/openshift.io#3862

### CODE REVIEW

**Comment by piyush-garg** [comment]
@gabemontero @hrishin 

Need little help

This PR is fixing the issue of PR build not getting reflected when a build is already going on.

Also, this cancels the previous PR build going on and starts a new build. 

But when PR build is in a queue and I push one more commit in PR, then it only builds one. I want something like If PR is in the queue, and when it gets scheduled if a new commit is there it should cancel the previous build and schedules new.

Any thoughts on how this can be achieved. Thanks

**Comment by gabemontero** [comment]
Seems like `Jenkins.getInstance().getQueue().cancel(wj)` would remove the job you specify from the queue

`WorkflowJob` implements `Item` and so you should be able to pass it into the cancel method

**Comment by piyush-garg** [comment]
@gabemontero Would be good if you can review this, It is fixing the issue.

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java [hunk 1]
```diff
@@ -107,7 +109,22 @@ public boolean shouldSchedule(Queue.Task p, List<Action> actions) {
         logger.info("Triggering OpenShift Build for WorkflowJob " + wj.getFullName() + " due to " + causeDescription(actions));
         BuildConfig foundBuildConfig = OpenShiftUtils.findBCbyNameOrLabel(getOpenShiftClient(), namespace, buildConfigname);
         if (foundBuildConfig != null) {
+          int buildInJenkins = wj.getLastBuild()!=null ? wj.getLastBuild().number : 0;
           buildConfigname = foundBuildConfig.getMetadata().getName();
+          if (isPRBuild && (buildInJenkins > 0 || (buildInJenkins == 0 && isJobInQueue(wj)))) {
+            if (isJobInQueue(wj)){
+              cancelBuildRequest(buildConfigname, namespace, wj.getNextBuildNumber());
+              Jenkins.getInstance().getQueue().cancel(wj);
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java]: Was searching Jenkins for some usages of this and discovered that Jimmi had a version of this already in JenkinsUtils ... see https://github.com/fabric8io/jenkins-sync-plugin/blob/job-to-bc/src/main/java/io/fabric8/jenkins/openshiftsync/JenkinsUtils.java#L256-L292

Even if you need a slightly modified versions of those current foms, you should place whatever new flavor of the cancel queued build function you derive in JenkinsUtils.java, and leverage the same impersonate pattern applied there.
@gabemontero

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java [hunk 2]
```diff
@@ -127,6 +144,23 @@ private void triggerBuildRequest(String buildConfigname, String namespace, Strin
       );
   }
 
+  private void cancelBuildRequest(String buildConfigname, String namespace, int number) {
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java]: Move this to OpenShiftUtils and create a new versions of the method updateOpenShiftBuildPhase at https://github.com/fabric8io/jenkins-sync-plugin/blob/job-to-bc/src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java#L416-L422 that takes some extra params to set the trigger by and message params you want here.  Then have the original method with less params call the new one with more params, where you don't call editTriggerBy or withMessage if the params are empty or null

**Review by gabemontero — CHANGES_REQUESTED** [review]
Requested  couple of changes to address reuse and acl needs

**Comment by piyush-garg** [comment]
@gabemontero Is this look good to you now?

File: src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration.java [hunk 3]
```diff
@@ -59,13 +61,14 @@
...
   @DataBoundConstructor
-  public GlobalPluginConfiguration(boolean enable, String server, String namespace, String jobNamePattern, String skipOrganisationPrefix, String skipBranchSuffix) {
+  public GlobalPluginConfiguration(boolean enable, String server, String namespace, String jobNamePattern, String skipOrganisationPrefix, String skipBranchSuffix, boolean cancelPRbuildOnUpdate) {
     this.enabled = enable;
     this.server = server;
     this.namespace = namespace;
     this.jobNamePattern = jobNamePattern;
     this.skipOrganisationPrefix = skipOrganisationPrefix;
     this.skipBranchSuffix = skipBranchSuffix;
+    this.cancelPRBuildOnUpdate = cancelPRbuildOnUpdate;
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration.java:71]: Shouldn't there be a config panel change to go along with this addition to the config.

File: src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java [hunk 4]
```diff
@@ -413,14 +414,44 @@ public static void updateGitSourceUrl(BuildConfig buildConfig, String gitUrl, St
     gitSource.setRef(ref);
   }
 
+  public static void updateOpenShiftBuildPhaseAndTriggerMessage(Build build, String phase, String message) {
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java]: Just call this `updateOpenShiftBuildPhase` ... Java will allow the 2 versions with one having a super set param list of the other

**Review by gabemontero — CHANGES_REQUESTED** [review]
Yep getting close .... see the two comments below

File: src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java (hunk 4 above)
Comment (piyush-garg) [reply src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java]: ok, sounds good

File: src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration.java (hunk 3 above)
Comment (piyush-garg) [reply src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration.java:71]: Can you guide me how to do that, no idea and experience with this.

We are setting these value using configMap and it's getting reflected.

**Comment by piyush-garg** [comment]
@gabemontero Addressed both the comments.

File: src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration.java (hunk 3 above)
Comment (gabemontero) [reply src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration.java:71]: good job - you found it below  ... will comment further there

File: src/main/resources/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration/config.jelly [hunk 5]
```diff
@@ -42,5 +42,9 @@
              description="What branch name suffix should we omit from the generated OpenShift BuildConfig resources created by the sync plugin.  Its common to use a common branch name like `master` which we can omit from names to avoid noise.">
       <f:textbox/>
     </f:entry>
+    <f:entry title="Cancel PR Build On Update" field="cancelPRBuildOnUpdate"
+             description="Enabling this feature will cancel the previous build and schedule new one if PR gets updated while the previous build is in progress or in queue">
+      <f:textbox/>
```
Comment (gabemontero) [inline src/main/resources/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration/config.jelly]: Use <f:checkbox/>

See the "Enabled" field above as an example

**Review by gabemontero — CHANGES_REQUESTED** [review]
Just one minor change and I think we are good to go

File: src/main/resources/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration/config.jelly (hunk 5 above)
Comment (piyush-garg) [reply src/main/resources/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration/config.jelly]: nice observation

**Comment by piyush-garg** [comment]
@gabemontero All set I think

**Review by gabemontero — APPROVED** [review]
LGTM

**Comment by piyush-garg** [comment]
Thanks, @gabemontero for all the help you provide. Thanks a lot.

File: src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration.java (hunk 3 above)
Comment (hrishin) [reply src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration.java:71]: @gabemontero you mean updating its jelly file?

**Review by hrishin — APPROVED** [review]

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java [hunk 6]
```diff
@@ -107,26 +111,33 @@ public boolean shouldSchedule(Queue.Task p, List<Action> actions) {
         logger.info("Triggering OpenShift Build for WorkflowJob " + wj.getFullName() + " due to " + causeDescription(actions));
         BuildConfig foundBuildConfig = OpenShiftUtils.findBCbyNameOrLabel(getOpenShiftClient(), namespace, buildConfigname);
         if (foundBuildConfig != null) {
+          int buildInJenkins = wj.getLastBuild()!=null ? wj.getLastBuild().number : 0;
           buildConfigname = foundBuildConfig.getMetadata().getName();
-          triggerBuildRequest(buildConfigname, namespace, jobURL);
+          if (isPRBuild && cancelPRBuildOnUpdate && (buildInJenkins > 0 || (buildInJenkins == 0 && isJobInQueue(wj)))) {
```
Comment (sthaha) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java:116]: instead of nesting, you may be able to make it flatter (easier to understand) if you exit early; e.g.

```java
if (foo) {
  something()
  if (bar) {
    somethingElse();
      if (bar) {
        someMoreThings()
      }
  }
}
```

can be better written as 
```java

if (!foo) {
  return 
}
something()

if (!bar) {
return
}
somethingElse()

if (!baz) {
  return
}

someMoreThings();

```
