### PR TITLE
fixes build progress state sync

### LINKED ISSUE #3935: Intermittent error - Jenkins log reports success - but promote button is not displayed in the OSIO UI
Steps to recreate (this issue is not reproducible at will):
* Create new project
* Observe build success and option to promote to run in Jenkins log
* Observe promote button is not displayed in OSIO UI

05-02-jenkins-log-failed

05-01-pipeline-failed

Full set of test artifacts (logs, screenshots) are available here:
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/262/

### PR DESCRIPTION
**Pull request by hrishin**
Issue:
Sometimes sync plugin is not synchronizing the build
run state correctly. That's resulting in intermittent
behavior like doesn't update waiting input state in OS build.
Such issue is occurring because `BuildSyncRunListener`  polls
Jenkins build run state periodically and update the status
in OS build on some conditions. Deriving such conditions
is kind of error-prone in some cases.
Also, polling at a fixed interval wasting some CUP cycles.

Fix:
Instead of polling based approach `BuildSyncRunListener` listens the Jenkins run
step events and updates status in OS build resources.

Resolves https://github.com/openshiftio/openshift.io/issues/3935

### CODE REVIEW

**Comment by hrishin** [comment]
@gabemontero could you please review if possible?

**Comment by gabemontero** [comment]
sure thing @hrishin - just have a couple of deadlines coming up, but I should be able to get to it Wednesday afternoon US ET.

**Comment by hrishin** [comment]
Thank you! @gabemontero

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java [hunk 1]
```diff
@@ -36,494 +18,316 @@
...
-      .replaceAll("/#", "#")
-      .replaceAll(":/", "://");
-  }
-
-  private void init() {
-    namespace = OpenShiftUtils.getNamespaceOrUseDefault(namespace, getOpenShiftClient());
+  public BuildSyncRunListener(OpenShiftClient ocClient, String ns) {
+    openShiftClient = ocClient;
+    namespace = OpenShiftUtils.getNamespaceOrUseDefault(ns, openShiftClient);
+    updateExecutor = Executors.newSingleThreadExecutor();
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java]: The executor needs to be static, where you create a pool of say 25, and where the pool size is configurable (a sys prop vs. an explicit config field is fine).  

Our experience has been that clean up of these executors is non-existent, and we saw thread leaks as multiple invocations occurred over time.

Certainly when you consider this is a per namespace thing per the ctor args and we could see BuildSyncRunListener getting created many times over long running Jenkins instances.

**Review by gabemontero — CHANGES_REQUESTED** [review]
Overall really cool @hrishin 

Just one change I believe should be made (we had to do this recently with our client plugin).

Any chance you could try and cherry pick this into https://github.com/openshift/jenkins-sync-plugin PR (where you filter out other differences in these two versions as needed) ?

If not, we'll see about trying to port this at some point.

@bparees FYI

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java (hunk 1 above)
Comment (hrishin) [reply src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java]: > The executor needs to be static, where you create a pool of say 25, and where the pool size is configurable (a sys prop vs. an explicit config field is fine).

You mean using `newFixedThreadPool()` Or definate queue size?

> Certainly when you consider this is a per namespace thing per the ctor args and 

I'm sorry, I didn't get this point. Could you please elaborate it?

> we could see BuildSyncRunListener getting created many times over long running Jenkins instances.

Oh, thank you for sharing this observation. I wasn't aware of this case. So it's in general Jenkins behavior? My impression is `@Extension` class is a singleton and its get initialized only once throughout the lifecycle of Jenkins.

**Comment by hrishin** [comment]
@gabemontero Thank you for the first review. I will accommodate your review comments.

Another issue I found is, if a build fails at the beginning then this patch don't update build state on `RunListener`s `onCompleted()` and `onDeleted()`. Hence it would not update the build status because in that case no step gets executed.

I'm going to fix this issue, will update the patch.  

cc: @piyush-garg

**Comment by hrishin** [comment]
@piyush-garg @gabemontero I've tested following scenarios. Let me know if we need to test more.

|                                 | success | aborted | failed |
|---------------------------------|---------|----------|--------|
| 1 build                         | pass    | pass     | pass   |
| 2 builds (concurrent)           | pass    | pass     | pass   |
| 2 builds (1 blocking 1 running) | pass    | pass     | pass   |
| 2 builds (2 builds of same workflow) | pass    | pass     | pass   |

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java (hunk 1 above)
Comment (gabemontero) [reply src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java]: General java behavior really, though Jenkins does not do anything to help.

But yeah, I got mixed up a bit by your Constructor with its params that I ignored the @Extension piece.   So 
a) in the fabric8 version of this plugin, you've got namespace set on this object, where presumably you have only 1 namesapce to deal with in your scenarios, right ?
b) yeah, the params in the constructor has to do with Jenkins rehydrating the object on restart

If I have that right, it is fine for you.  But if we are to pick this upstream, based on how we reconciled things, since we support multiple namespaces being monitored, we would want the executor pool globalized.

Still sorting through your the rest of your new commits, but let's sort out these details one way or the other.

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildStateUpdater.java [hunk 2]
```diff
@@ -43,84 +39,56 @@
...
-  private OpenShiftClient openShiftClient;
+  private static BuildStateUpdater instance;
+  private final transient ExecutorService threadExecutor;
 
-  public BuildSyncRunListener() {
-    openShiftClient = getOpenShiftClient();
-    namespace = OpenShiftUtils.getNamespaceOrUseDefault(namespace, openShiftClient);
-    updateExecutor = Executors.newSingleThreadExecutor();
+  private BuildStateUpdater() {
+    this.threadExecutor = Executors.newSingleThreadExecutor();
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/BuildStateUpdater.java:52]: ah ha ... so you've factored out the namespace from this and made it a singleton

All these changes and renames will make it harder to pick this fix into upstream ... but these 2 versions of sync plugin are sooo divergent now ... merging them will require some form of detailed top down analysis

Since we are not getting reports of the original error, I think we should wait for pulling in this individual commit.

I'll mull it over here on my end, cross reference with my team here, but that is my current leaning.

**Comment by gabemontero** [comment]
Nothing else jumped out at me @hrishin ... lgtm

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java (hunk 1 above)
Comment (hrishin) [reply src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java]: >  in the fabric8 version of this plugin, you've got namespace set on this object, where presumably you have only 1 namesapce to deal with in your scenarios, right ?

Yes

> If I have that right, it is fine for you. But if we are to pick this upstream, based on how we reconciled things, since we support multiple namespaces being monitored, we would want the executor pool globalized.

I see. On other note in this patch updater `update()` is taking namespace as the second parameter. So its no more fixed with a constructor. However, consumer of the class has to derive the right namespace.

Really appreciate for bringing this point.

File: src/main/java/io/fabric8/jenkins/openshiftsync/BuildStateUpdater.java (hunk 2 above)
Comment (hrishin) [reply src/main/java/io/fabric8/jenkins/openshiftsync/BuildStateUpdater.java:52]: > but these 2 versions of sync plugin are sooo divergent now ... merging them will require some form of detailed top down analysis

Agreed, :(

**Review by piyush-garg — APPROVED** [review]
LGTM
